### ISSUE TITLE
I am trying this steps with open source jfrog artifactory but not working

### ISSUE THREAD

**Issue by hardikkaji** [upgradingdave/javajing#1]
I have tried all steps but when i am creating project in netbeans IDE 7.3
Getting below error

No plugin found for prefix 'archetype' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (D:\maven\MavenRepo), central (http://repo1.maven.org/maven2), upgradingdave-ro (http://localhost:8081/artifactory/repo)] -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException

Please kindly suggest.

Regards,
Hardik Kaji

**Comment by hardikkaji** [comment]
Please reply me. 

Please see below code for maven settings.xml 

Regards, 
Hardik Kaji

![setting xml](https://f.cloud.github.com/assets/4531780/2242471/324d6fbc-9d04-11e3-8e0e-51d9828c2d1e.png)

**Comment by dparoulek** [comment]
Hi Hardik, 

What do you see when you run `mvn -e install` from the command line?

**Comment by hardikkaji** [comment]
Where should write this command.

I am using NETBeans IDE 7.3 for development.
When i am trying to create project on that time only i am getting above error.

So guide me to run this command.

I am new to MAVEN.
So Please help me out and Thanks for quick response.

Thanks & Regards,
Hardik Kaji

**Comment by upgradingdave** [comment]
Hi Hardik, I remember being new to Maven and it can be intimidating indeed! 

I highly recommend reading this book: http://www.sonatype.com/resources/books/maven-the-complete-reference. After I read read it cover to cover, I had a much better understanding of maven and was able to use the tool to be much more productive. 

Good Luck!

Dave
